import { Sparkles, Info, MailCheck } from "lucide-react";
import Avatar from "../common/Avatar";
import Button from "../common/Button";
import ApplicantStatusBadge from "./ApplicantStatusBadge";
import MatchBadge from "./MatchBadge";

export default function ApplicantCard({ applicant, onSelectProfile, onAccept, onReject, onRevoke, onReconsider }) {
  const isInvitation = applicant.source === "invitation";

  return (
    <div className="rounded-2xl border border-purple-200/60 bg-white p-5">
      <div className="flex items-center justify-between gap-4">
        <button
          type="button"
          onClick={() => onSelectProfile(applicant)}
          className="-ml-1 flex cursor-pointer items-center gap-3 rounded-full py-1 pr-3 transition-colors hover:bg-purple-50 text-left"
        >
          <Avatar src={applicant.volunteerAvatarUrl} name={applicant.volunteerName} size={44} />
          <span className="font-sora text-sm font-bold text-purple-600">{applicant.volunteerName}</span>
        </button>

        <ApplicantStatusBadge status={applicant.status} />
      </div>

      <div className="mt-4 flex flex-col gap-3">
        <div className="flex items-center justify-between rounded-xl border border-purple-100 bg-purple-50/40 px-4 py-3">
          <span className="font-sora text-xs font-bold uppercase tracking-wider text-purple-600">
            Picked Task
          </span>
          <span className="font-inter text-sm font-semibold text-purple-600/50">
            {applicant.taskName}
          </span>
        </div>

        {!isInvitation && (applicant.organizerReasoning || applicant.matchResult) && (
          <div className="rounded-xl border border-purple-200/70 bg-purple-50/80 p-4">
            <div className="mb-2 flex items-center justify-between gap-2">
              <div className="flex items-center gap-1.5 font-sora text-xs font-bold uppercase tracking-wider text-purple-600">
                <Sparkles className="h-3.5 w-3.5" />
                <span>AI Note</span>

                <div className="group relative flex items-center">
                  <Info className="h-3.5 w-3.5 cursor-pointer text-purple-400 transition-colors hover:text-purple-600" />

                  <div className="pointer-events-none absolute bottom-full left-1/2 mb-2 hidden -translate-x-1/2 flex-col gap-1 w-60 rounded-xl bg-purple-100 p-3 text-[11px] font-normal normal-case leading-snug text-purple-600/80 shadow-xl z-20 group-hover:flex">
                    <span className="font-semibold text-purple-600">About AI Note</span>
                    <span>
                      This recommendation is generated by AI to assist your review process. Result may not always be 100% accurate, so please verify details before deciding.
                    </span>
                    <div className="absolute top-full left-1/2 -translate-x-1/2 border-4 border-purple-200/60" />
                  </div>
                </div>
              </div>

              <MatchBadge matchResult={applicant.matchResult} />
            </div>

            {applicant.organizerReasoning && (
              <p className="font-inter text-sm leading-relaxed text-purple-600/50">
                {applicant.organizerReasoning}
              </p>
            )}
          </div>
        )}
      </div>

      <div className="mt-4 border-t border-purple-200/60 pt-4 flex justify-end gap-3">
        {isInvitation ? (
          <span className="inline-flex items-center gap-1.5 rounded-full border border-purple-200 bg-purple-50 px-3 py-1 font-sora text-xs font-bold text-purple-600">
            <MailCheck className="h-3.5 w-3.5 text-purple-600" />
            Joined Via Invite
          </span>
        ) : (
          <>
            {applicant.status === "submitted" && (
              <>
                <Button variant="danger" onClick={() => onReject(applicant)}>
                  Not This Time
                </Button>
                <Button variant="primary" onClick={() => onAccept(applicant)}>
                  Add To Team
                </Button>
              </>
            )}
            {applicant.status === "approved" && (
              <Button variant="danger" onClick={() => onRevoke(applicant)}>
                Remove From Team
              </Button>
            )}
            {applicant.status === "rejected" && (
              <Button variant="secondary" onClick={() => onReconsider(applicant)}>
                Reconsider
              </Button>
            )}
          </>
        )}
      </div>
    </div>
  );
}